version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-stuff:/var/lib/postgresql/data
  my_backend:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '4567:4567'
    env_file: .env