version: '3.1'

services:

  database:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
    volumes:
      - postgres-stuff/var/lib/postgresql/data
  my_backend:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '4567:4567'
    env_file: .env
    
  mainapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "4567:4567"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: database
