version: '3.1'

services:

  database:
    image: postgres:latest
    restart: always
    environment:
      - env_file: .env
    ports:
      - '5432:5432'
  my_backend:
    build: .
    depends_on:
      - database
    ports:
      - '8080:8080'
    


